title: Arabinda Nayak
logo: /assets/img/WhatsApp Image 2023-04-12 at 8.04.07 PM.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
